<?php

namespace Senio\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionnaireRepository extends EntityRepository
{
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT q FROM CoreBundle:questionnaire q 
                                   ORDER BY q.created DESC')
                    ->getResult();
    }
    public function getQuestionnaireResults()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT q.browser, count(q.id) FROM CoreBundle:questionnaire q 
                                   GROUP BY q.browser')
                    ->getResult();
    }
    public function getNumOfVotes()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT count(q.id) FROM CoreBundle:questionnaire q')
                    ->getResult();
    }
}
